### ISSUE TITLE
Crush The End.

### ISSUE THREAD

**Issue by DoctorFTB** [knoxhack/MMD-Public-Server#6]
I found portal to the End, joined. I climbed to top, kill mobs and dig ore's. Next was a crash.

**Comment by synthetixa** [comment]
Do you  have a crash report?

**Comment by DoctorFTB** [comment]
Client not crushed. Only server.

**Comment by Zaweri** [comment]
He mined Endimium ore or somesuch from Terraqueous. http://pastebin.com/FzNUS99g

**Comment by knoxhack** [comment]
ok fixed
