### ISSUE TITLE
Game crash when I attempt to remove Apiarist Backpack from Refined Storage System

### ISSUE THREAD

**Issue by pactuslupus** [knoxhack/MMD-Public-Server#8]
Unfortunately it doesn't generate a bug report. However, the error I get is

"Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes"

The backpack has several dozen bees in it, with about half of them being analyzed...if that is important. The system is powered by Ender IO stirling generator...again if that is important.

Doctor_FTB has replicated the same bug.

**Comment by RacerDelux** [comment]
Pactus please report this to both mod authors

**Comment by pactuslupus** [comment]
The Refined Storage author closed the issue report in the Forestry Github and assumed responsibility. However, he requested I update to minecraft 1.10.

**Comment by RacerDelux** [comment]
The server is already on 1.10.2, this is not an issue.
